import { HealthOverview, MedicationSchedule, EmergencyContact } from '../types';

export const MOCK_HEALTH_OVERVIEW: HealthOverview = {
  overallScore: 94,
  status: 'optimal',
  statusMessage: 'Vitals stable. Heart rate & SpO2 in normal range.',
  lastAssessmentTime: '10 mins ago',
  heartRate: {
    id: 'vital_hr',
    type: 'heart_rate',
    label: 'Heart Rate',
    value: 72,
    unit: 'BPM',
    trend: 'stable',
    trendValue: 'Normal rhythm',
    risk: 'optimal',
    lastUpdated: '5m ago',
    history: [
      { time: '06:00', value: 65 },
      { time: '09:00', value: 74 },
      { time: '12:00', value: 78 },
      { time: '15:00', value: 72 },
      { time: '18:00', value: 70 },
      { time: '21:00', value: 72 },
    ],
  },
  bloodPressure: {
    id: 'vital_bp',
    type: 'blood_pressure',
    label: 'Blood Pressure',
    value: '122/78',
    unit: 'mmHg',
    trend: 'stable',
    trendValue: 'Optimal',
    risk: 'optimal',
    lastUpdated: '15m ago',
    history: [
      { time: '06:00', value: 120 },
      { time: '09:00', value: 125 },
      { time: '12:00', value: 122 },
      { time: '15:00', value: 121 },
      { time: '18:00', value: 122 },
    ],
  },
  spo2: {
    id: 'vital_spo2',
    type: 'spo2',
    label: 'Oxygen Saturation',
    value: 98,
    unit: '%',
    trend: 'up',
    trendValue: '+1%',
    risk: 'optimal',
    lastUpdated: '2m ago',
    history: [
      { time: '06:00', value: 97 },
      { time: '09:00', value: 98 },
      { time: '12:00', value: 98 },
      { time: '15:00', value: 99 },
      { time: '18:00', value: 98 },
    ],
  },
  sleep: {
    id: 'vital_sleep',
    type: 'sleep',
    label: 'Sleep Quality',
    value: 7.8,
    unit: 'hrs',
    trend: 'up',
    trendValue: '86% Deep Sleep',
    risk: 'optimal',
    lastUpdated: 'Today',
    history: [
      { time: 'Mon', value: 6.5 },
      { time: 'Tue', value: 7.2 },
      { time: 'Wed', value: 7.0 },
      { time: 'Thu', value: 8.1 },
      { time: 'Fri', value: 7.8 },
    ],
  },
  steps: {
    id: 'vital_steps',
    type: 'steps',
    label: 'Daily Activity',
    value: 3420,
    unit: 'steps',
    trend: 'up',
    trendValue: '68% of daily goal',
    risk: 'optimal',
    lastUpdated: '1m ago',
    history: [
      { time: 'Mon', value: 2800 },
      { time: 'Tue', value: 4100 },
      { time: 'Wed', value: 3900 },
      { time: 'Thu', value: 3100 },
      { time: 'Fri', value: 3420 },
    ],
  },
};

export const MOCK_MEDICATION_SCHEDULE: MedicationSchedule = {
  todayAdherenceRate: 88,
  medications: [
    {
      id: 'med_01',
      name: 'Amlodipine Besylate',
      dosage: '5 mg',
      frequency: 'Once Daily',
      scheduledTime: '08:00 AM',
      status: 'taken',
      instructions: 'Take after breakfast with water.',
      pillColorHex: '#FF6B4A',
      remainingPills: 22,
      totalPills: 30,
    },
    {
      id: 'med_02',
      name: 'Metformin HCl',
      dosage: '500 mg',
      frequency: 'Twice Daily',
      scheduledTime: '01:30 PM',
      status: 'pending',
      instructions: 'Take during or after lunch.',
      pillColorHex: '#14B8A6',
      remainingPills: 14,
      totalPills: 60,
    },
    {
      id: 'med_03',
      name: 'Atorvastatin Calcium',
      dosage: '10 mg',
      frequency: 'Nightly',
      scheduledTime: '09:00 PM',
      status: 'pending',
      instructions: 'Take before sleep.',
      pillColorHex: '#3B82F6',
      remainingPills: 28,
      totalPills: 30,
    },
  ],
};

export const MOCK_EMERGENCY_CONTACTS: EmergencyContact[] = [
  {
    id: 'contact_01',
    name: 'Rajesh Sharma',
    relation: 'Son (Primary Guardian)',
    phone: '+91 98123 45678',
    isPrimary: true,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
  },
  {
    id: 'contact_02',
    name: 'Priya Sharma',
    relation: 'Daughter-in-law',
    phone: '+91 98234 56789',
    isPrimary: false,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
  },
  {
    id: 'contact_03',
    name: 'Dr. Vikram Patel',
    relation: 'Family Cardiologist',
    phone: '+91 98980 12345',
    isPrimary: false,
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200',
  },
];
